### ISSUE TITLE
KDE Theme causes KWin to crash on sign-out

### ISSUE THREAD

**Issue by ran-dall** [dracula/gtk#143]
😁 Hello @EliverLara, I email you a few days ago, but haven't recieved a response...so I figuired I'd open this up...

Currently, the Global Plasma Dracula Theme is causing my KWin to crash, beyond repair, upon every sign-out. I've pasted the crash report I emailed to you, below.

```shell
Application: kwin_x11 (kwin_x11), signal: Segmentation fault

[KCrash Handler]
#4  0x00007f628aac52d7 in QThreadStorageData::get() const () from /usr/lib64/libQt5Core.so.5
#5  0x00007f628b1728c8 in QOpenGLContext::currentContext() () from /usr/lib64/libQt5Gui.so.5
#6  0x00007f628b175fbd in QOpenGLContext::destroy() () from /usr/lib64/libQt5Gui.so.5
#7  0x00007f628b176357 in QOpenGLContext::~QOpenGLContext() () from /usr/lib64/libQt5Gui.so.5
#8  0x00007f628b176369 in QOpenGLContext::~QOpenGLContext() () from /usr/lib64/libQt5Gui.so.5
#9  0x00007f628a69c4bd in __cxa_finalize () from /lib64/libc.so.6
#10 0x00007f628a51e613 in ?? () from /usr/lib64/libkwineffects.so.13
#11 0x00007ffe2ed0aeb0 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
[Inferior 1 (process 3538) detached]
```

🥇 Thanks for your help and awesome theme...

**Comment by ran-dall** [comment]
BTW, I tried updating my KWin from 5.21.5-r1 to 5.22.5, to see if perphaps this made a difference...but same error with 5.22.5.

**Comment by ran-dall** [comment]
I seem to have fixed it. 🔧

**As it turns out, NVIDIA GPUs feature their own compositing system (or pipeline, as they like to refer to it to), which turns out, gets intsalled with the proprietary NVIDIA GPU driver. This proprietary pipeline sytstem is supposed to produce better results than OpenGL, therefore things just seem to go a lot better with KWin and all KDE compositing turned off.** 

This seemes to have fixed the issue for me for now, however, I'll be issuing a PR with this new information so that anyone that has problems with this theme, KDE, and/or Kvantum with their NVIDIA GPU knows that turrning off compositing will fix any issues you have with KWin and this theme (and many other issues, like getting a black screen when going full screen while watching a vide on YouTube).
